var parent = document.querySelector("#main");
var child1 = document.getElementById("first");
var child2 = child1.nextSibling;
console.log(parent);
console.log(child1);
console.log(child1.nextElementSibling);
console.log(parent.lastElementChild);
console.log(child1.firstChild);
console.log(child1.nextSibling);
console.log(child2.nextSibling);
