var a=10;
var b=5;
 a+=b;
 sum=a+b;
 sub=a-b;
 mul=a*b;
 div=a/b;
 console.log("Sum of a and b:",sum);
 console.log("Subtraction of a and b:",sub);
 console.log("Multiplication of a and b:",mul);
 console.log("Division of a and b:",div);