import "./styles.css";
let array = [1.2, 3, 4, 5, 6];
console.log("Array 1", array);
let array2 = [1, 2, 3, 4];
array2.pop(1);
console.log("Array 2 pop", array2);
let array3 = [9, 8, 7, 6, 5];
let slicearray = array3.slice(1, 3);
console.log(slicearray);
let array4 = [3, 4, 5, 6, 7, 8];
let splicearray = array4.splice(1, 2);
console.log(splicearray);
